"""add_status_created_by_expires_at

Revision ID: 268251662868
Revises: da086fbdb95a
Create Date: 2026-01-12 16:51:14.241371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '268251662868'
down_revision: Union[str, Sequence[str], None] = 'da086fbdb95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('expires_at', sa.DateTime(), nullable=True))
    
    # Ajouter les colonnes comme nullable d'abord
    op.add_column('clinical_cases', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('clinical_cases', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Mettre à jour les valeurs existantes (tous les cas créés par user 1, status 'published')
    op.execute("UPDATE clinical_cases SET created_by = 1 WHERE created_by IS NULL")
    op.execute("UPDATE clinical_cases SET status = 'published' WHERE status IS NULL")
    
    # Rendre les colonnes NOT NULL
    op.alter_column('clinical_cases', 'created_by', nullable=False)
    op.alter_column('clinical_cases', 'status', nullable=False)
    
    op.create_index(op.f('ix_clinical_cases_created_by'), 'clinical_cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_clinical_cases_status'), 'clinical_cases', ['status'], unique=False)
    op.create_foreign_key(None, 'clinical_cases', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clinical_cases', type_='foreignkey')
    op.drop_index(op.f('ix_clinical_cases_status'), table_name='clinical_cases')
    op.drop_index(op.f('ix_clinical_cases_created_by'), table_name='clinical_cases')
    op.drop_column('clinical_cases', 'status')
    op.drop_column('clinical_cases', 'created_by')
    op.drop_column('attempts', 'expires_at')
    # ### end Alembic commands ###
