"""initial_schema_with_station_types_and_uuid

Revision ID: 73d322fd2429
Revises: 
Create Date: 2026-01-12 12:38:20.310542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73d322fd2429'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('station_type', sa.Enum('patient_interview', 'exam_analysis', 'procedure', 'diagnosis_announcement', 'mixed', name='stationtype'), nullable=False),
    sa.Column('student_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scenario_context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_cases_station_type'), 'clinical_cases', ['station_type'], unique=False)
    op.create_index(op.f('ix_clinical_cases_title'), 'clinical_cases', ['title'], unique=True)
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('cardiologie', 'pneumologie', 'nephrologie', 'infectiologie', 'hepatogastroenterologie', 'neurologie', 'geriatrie', 'endocrinologie', 'rhumatologie', 'hematologie', 'oncologie', 'psychiatrie', 'sante_publique', 'urgences', 'reanimation', 'urologie', 'gynecologie', 'pediatrie', 'medecine_legale', 'medecine_interne', 'optalmologie', 'orl', 'dermatologie', 'orthopedie', 'stomatologie', 'mpr', 'soins_palliatifs', 'medecine_travail', name='discipline'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('edn_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edn_items_number'), 'edn_items', ['number'], unique=True)
    op.create_index(op.f('ix_edn_items_title'), 'edn_items', ['title'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('casedisciplinelink',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'discipline_id')
    )
    op.create_table('caseednlink',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('edn_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], ),
    sa.ForeignKeyConstraint(['edn_id'], ['edn_items.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'edn_id')
    )
    op.create_table('edndisciplinelink',
    sa.Column('edn_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['edn_id'], ['edn_items.id'], ),
    sa.PrimaryKeyConstraint('edn_id', 'discipline_id')
    )
    op.create_table('evaluation_grids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_grids_case_id'), 'evaluation_grids', ['case_id'], unique=True)
    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_available_during_case', sa.Boolean(), nullable=False),
    sa.Column('trigger_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['clinical_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_case_id'), 'attachments', ['case_id'], unique=False)
    op.create_index(op.f('ix_attachments_kind'), 'attachments', ['kind'], unique=False)
    op.create_index(op.f('ix_attachments_mime_type'), 'attachments', ['mime_type'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('system', 'student', 'patient', name='chatrole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attachment_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_attachments_mime_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_kind'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_case_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_evaluation_grids_case_id'), table_name='evaluation_grids')
    op.drop_table('evaluation_grids')
    op.drop_table('edndisciplinelink')
    op.drop_table('caseednlink')
    op.drop_table('casedisciplinelink')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_edn_items_title'), table_name='edn_items')
    op.drop_index(op.f('ix_edn_items_number'), table_name='edn_items')
    op.drop_table('edn_items')
    op.drop_table('disciplines')
    op.drop_index(op.f('ix_clinical_cases_title'), table_name='clinical_cases')
    op.drop_index(op.f('ix_clinical_cases_station_type'), table_name='clinical_cases')
    op.drop_table('clinical_cases')
    # ### end Alembic commands ###
