"""add_completed_at_to_attempts

Revision ID: da086fbdb95a
Revises: 73d322fd2429
Create Date: 2026-01-12 12:49:09.722554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'da086fbdb95a'
down_revision: Union[str, Sequence[str], None] = '73d322fd2429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'completed_at')
    # ### end Alembic commands ###
