"""add_hashed_password_to_user

Revision ID: ff23949a4733
Revises: 268251662868
Create Date: 2026-01-14 08:09:02.978166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff23949a4733'
down_revision: Union[str, Sequence[str], None] = '268251662868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Étape 1: Ajouter la colonne comme nullable
    op.add_column('users', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Étape 2: Mettre une valeur par défaut pour les utilisateurs existants
    # Hash de "changeme123" - les utilisateurs devront changer leur mot de passe
    op.execute("UPDATE users SET hashed_password = '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5yrOXlGBJnP2.' WHERE hashed_password IS NULL")
    
    # Étape 3: Rendre la colonne NOT NULL
    op.alter_column('users', 'hashed_password', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
